---
version: "3.6"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    hostname: redis
    environment:
      REDIS_ARGS: --save 20 1 --appendonly yes
    restart: unless-stopped
    #   - "6379:6379"
    volumes:
      - "./app_data/redis:/data"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping", "|", "grep", "pong"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - sxkcd

  app:
    container_name: app
    hostname: app
    image: ghcr.io/kencx/sxkcd:latest
    build: .
    command: ["-f", "/data/comics.json"]
    # to download new data
    # entrypoint: ["./sxkcd", "download", "-f", "/data/comics.json"]
    restart: unless-stopped
    ports:
      - "6380:6380"
    volumes:
      - "./app_data/app:/data"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - proxy
      - sxkcd

networks:
  proxy:
    external: true
  sxkcd:
    name: sxkcd
