version: "3.6"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    hostname: redis
    networks:
      - sxkcd

  app:
    container_name: app
    hostname: app
    image: sxkcd:latest
    build: .
    depends_on:
      - redis
    networks:
      - proxy
      - sxkcd

networks:
  proxy:
    external: true
  sxkcd:
    name: sxkcd
