---
version: "3.6"
services:
  redis:
    image: redis/redis-stack-server:6.2.6-v9
    container_name: redis
    hostname: redis
    environment:
      REDIS_ARGS: --save 20 1 --appendonly yes
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - "./app_data/redis:/data"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping", "|", "grep", "pong"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - sxkcd

  app:
    container_name: sxkcd
    hostname: sxkcd
    image: ghcr.io/kencx/sxkcd:latest
    build:
      context: .
      tags:
        - latest
    # run "docker compose run --rm app download -f /data/comics.json" prior to starting
    command: ["server", "-p", "6380", "-r", "redis:6379", "-f", "/data/comics.json"]
    restart: unless-stopped
    ports:
      - "6380:6380"
    volumes:
      - "./app_data/app:/data"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - sxkcd

networks:
  sxkcd:
    name: sxkcd
