version: "3.6"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  app:
    container_name: app
    image: rkcd:latest
    build: .
    ports:
      - "6380:6380"
    depends_on:
      - redis
