version: "3.6"
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  app:
    container_name: app
    hostname: app
    image: rkcd:latest
    build: .
    ports:
      - "6380:6380"
    depends_on:
      - redis

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./deploy/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./deploy/certbot/www:/var/www/certbot/:ro"
      - "./deploy/certbot/conf/:/etc/nginx/ssl/:ro"
    depends_on:
      - redis
      - app

  certbot:
    container_name: certbot
    hostname: certbot
    image: certbot/certbot:latest
    volumes:
      - "./deploy/certbot/www/:/var/www/certbot/:rw"
      - "./deploy/certbot/conf/:/etc/letsencrypt/:rw"
    depends_on:
      - nginx
